spring:
  application:
    name: config-client
  config:
    import: "optional:configserver:"
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh